name: Daily COVID cases Data

on:
  schedule:
    - cron: "30 4 * * *" # Runs daily at 10:00 AM IST (03:30 UTC)
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest COVID data
        run: |
          curl -sSL "https://covid19dashboard.mohfw.gov.in/data/datanew.json" -o data/today.json

      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git switch gh-pages

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit data if changed
        run: |
          git add data/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update COVID data (automated)"
            git push
          else
            echo "No changes to commit"
          fi
