name: Daily COVID cases Data

on:
  schedule:
    - cron: "30 4 * * *" # Runs daily at 10:00 AM IST (03:30 UTC)
  workflow_dispatch:

env:
  COMMIT_BRANCH: "gh-pages"

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest COVID data
        run: |
          curl -sSL "https://covid19dashboard.mohfw.gov.in/data/datanew.json" -o data/today.json

      - name: Git push
        uses: rsb-23/actions/git-push@main
        with:
          git_user: "gh-pages[bot]"
          files: "data/"
          commit_message: "chore: update COVID data (automated)"
          branch: "gh-pages"
